### ISSUE TITLE
Windows and Linux Memory collector gauge names are different

### ISSUE THREAD

**Issue by No0Vad** [Daniel15/prometheus-net.SystemMetrics#7]
Currently the gauge names are different for Windows and Linux, and that is to be expected since they report different amount of metrics. But it is making it more difficult to create graph and alerts in Grafana.

My suggestion is to either add `node_memory_MemoryLoad` to the Linux collector.
Or `node_memory_MemAvailable_bytes` and `node_memory_MemTotal_bytes` to the Windows collector.

That way it will be easier to create a graph and alert for them both in Grafana.

**Comment by Daniel15** [comment]
> Or node_memory_MemAvailable_bytes and node_memory_MemTotal_bytes to the Windows collector.

This seems reasonable to me. I'll just have to make sure they're measuring exactly the same thing.

Also note that in Grafana, you can add multiple metrics to a single graph.

**Comment by No0Vad** [comment]
> Also note that in Grafana, you can add multiple metrics to a single graph.

Yeah, I have that right now and it works great, but sadly it also means I have to create 2 alert rules, instead of 1 alert rule.

**Comment by Daniel15** [comment]
@No0Vad  I'm going to add the `_bytes` suffix to all the Windows memory counters.

I'm trying to figure out if the `MemFree` on Windows is closer to `MemFree` or `MemAvailable` on Linux. Microsoft's documentation on the `ullAvailPhys` field I'm using (https://learn.microsoft.com/en-us/windows/win32/api/sysinfoapi/ns-sysinfoapi-memorystatusex) says:

> The amount of physical memory currently available, in bytes. This is the amount of physical memory that can be immediately reused without having to write its contents to disk first. It is the sum of the size of the standby, free, and zero lists.

But it's unclear to me whether this includes memory used for caching or not.

On Linux, `MemFree` is the amount of physical RAM that's free, whereas `MemAvailable` is `MemFree` plus any memory that can be immediately freed (caches, buffers, reclaimable kernel RAM slabs, etc), so `MemAvailable` is usually what you really care about.

Microsoft saying "The amount of physical memory currently available" implies it's like `MemFree`, but then saying "This is the amount of physical memory that can be immediately reused without having to write its contents to disk first" implies it's like `MemAvailable` as read caches would not need to be written to disk in order to free them.

What do you think?

**Comment by No0Vad** [comment]
Sadly I don't know either what they mean. But I'm on Windows and I found how to get the information for MEMORYSTATUSEX using C# and decided to test it. And this is what the code returns on my system:

|          Field          |      Value      |
| ----------------------- | --------------- |
| dwLength                | 64              |
| dwMemoryLoad            | 25              |
| ullTotalPhys            | 34268815360     |
| `ullAvailPhys`            | `25503285248`     |
| ullTotalPageFile        | 36818952192     |
| ullAvailPageFile        | 22212468736     |
| ullTotalVirtual         | 140737488224256 |
| ullAvailVirtual         | 140455452286976 |
| ullAvailExtendedVirtual | 0               |


And what Resource Monitor reports for me and my memory usage
![image](https://github.com/Daniel15/prometheus-net.SystemMetrics/assets/9308455/2ce95df4-6bf9-4b8e-bf49-83dba7786cfd)

The tooltip for the labels shown in the image are these:

**Hardware Reserved**
Memory that is reserved for use by the BIOS and some drivers for other peripherals.

**In use**
Memory used by processes, drivers, or the operating system.

**Modified**
Memory whose contents must be written to disk before it can be used for another purpose.

**Standby**
Memory that contains cached data and code that is not actively in use.

**Free**
Memory that does not contain any valuable data and that will be used first when processes, drivers or the operating system need more memory.


**Available**
Amount of memory (including Standby and Free memory) that is immediately available for use by processes, drivers or the operating system.

**Cached**
Amount of memory (including Standby and Modified memory) containing cached data and code for rapid access by processes, drivers and the operating system.

**Total**
Amount of physical memory available to the operating system, device drivers, and processes.

**Installed**
Amount of physical memory installed in the computer.


There is 2-4 seconds between the images, but I hope it helps you figure out what `ullAvailPhys` actually is.

**Comment by Daniel15** [comment]
From your info above, and from https://github.com/oshi/oshi/issues/23, it sounds like `ullAvailPhys` is actually "available" memory. Thanks for the info :)

**Comment by Daniel15** [comment]
Fixed in v3.0
